import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import AuthProvider from "@/providers/auth";
import { ProvidersWrapper } from "@/providers/ProvidersWrapper";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Controle de Estoque",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("RootLayout montado.");

  return (
    <html lang="pt-br">
      <body
        className={cn("min-h-screen font-sans antialiased", fontSans.variable)}
      >
        <ProvidersWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ProvidersWrapper>
      </body>
    </html>
  );
  // return (
  //   <html lang="pt-br">
  //     <body
  //       className={cn("min-h-screen font-sans antialiased", fontSans.variable)}
  //     >
  //       <AuthProvider>
  //         <ThemeProvider
  //           attribute="class"
  //           defaultTheme="system"
  //           enableSystem
  //           disableTransitionOnChange
  //         >
  //           {children}
  //         </ThemeProvider>
  //       </AuthProvider>
  //     </body>
  //   </html>
  // );
}
